import type {
  Property,
  PropertyRiskProfile,
  InsuranceCostEstimate,
  CarriersResult,
  InsurabilityStatus,
  AnalyticsSummary,
  Client,
  User,
} from './shared/types'

export const mockProperties: Property[] = [
  {
    id: 'prop_1',
    address: '123 Palm Beach Rd',
    city: 'Miami',
    state: 'FL',
    zip: '33139',
    county: 'Miami-Dade',
    lat: 25.7617,
    lng: -80.1918,
    propertyType: 'SINGLE_FAMILY',
    yearBuilt: 2015,
    squareFeet: 2450,
    bedrooms: 4,
    bathrooms: 3,
    lotSize: 8500,
    estimatedValue: 875000,
    lastSalePrice: 725000,
    lastSaleDate: '2022-06-15',
    parcelId: '01-4455-0023-0010',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prop_2',
    address: '456 Sunset Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90028',
    county: 'Los Angeles',
    lat: 34.0937,
    lng: -118.3287,
    propertyType: 'CONDO',
    yearBuilt: 2019,
    squareFeet: 1850,
    bedrooms: 3,
    bathrooms: 2,
    lotSize: null,
    estimatedValue: 1250000,
    lastSalePrice: 1100000,
    lastSaleDate: '2023-03-22',
    parcelId: '5544-012-035',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prop_3',
    address: '789 Oak Street',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    county: 'Travis',
    lat: 30.2672,
    lng: -97.7431,
    propertyType: 'SINGLE_FAMILY',
    yearBuilt: 2008,
    squareFeet: 3200,
    bedrooms: 5,
    bathrooms: 4,
    lotSize: 12000,
    estimatedValue: 950000,
    lastSalePrice: 780000,
    lastSaleDate: '2021-11-08',
    parcelId: '02-1234-0001',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prop_4',
    address: '321 Mountain View Dr',
    city: 'Denver',
    state: 'CO',
    zip: '80202',
    county: 'Denver',
    lat: 39.7392,
    lng: -104.9903,
    propertyType: 'TOWNHOUSE',
    yearBuilt: 2020,
    squareFeet: 2100,
    bedrooms: 3,
    bathrooms: 2.5,
    lotSize: 3500,
    estimatedValue: 685000,
    lastSalePrice: 620000,
    lastSaleDate: '2023-08-14',
    parcelId: '0245-00-001-000',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prop_5',
    address: '555 Harbor Lane',
    city: 'Charleston',
    state: 'SC',
    zip: '29401',
    county: 'Charleston',
    lat: 32.7765,
    lng: -79.9311,
    propertyType: 'SINGLE_FAMILY',
    yearBuilt: 1985,
    squareFeet: 2800,
    bedrooms: 4,
    bathrooms: 3,
    lotSize: 9200,
    estimatedValue: 720000,
    lastSalePrice: 595000,
    lastSaleDate: '2020-04-20',
    parcelId: '460-03-00-045',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockRiskProfile: PropertyRiskProfile = {
  propertyId: 'prop_1',
  overallRiskLevel: 'HIGH',
  overallRiskScore: 68,
  flood: {
    level: 'HIGH',
    score: 72,
    trend: 'WORSENING',
    description: 'Property is located in a Special Flood Hazard Area (SFHA) with high risk of flooding.',
    details: [
      'Located in FEMA Flood Zone AE',
      'Base Flood Elevation is 8 feet',
      '26% annual chance of flooding over 30-year mortgage',
      'Historical claims in this ZIP code are 2.5x national average',
    ],
    dataSource: 'FEMA NFHL',
    lastUpdated: new Date().toISOString(),
    floodZone: 'AE',
    firmPanelId: '12086C0361M',
    baseFloodElevation: 8,
    inSpecialFloodHazardArea: true,
    annualChanceOfFlooding: 1,
  },
  fire: {
    level: 'LOW',
    score: 18,
    trend: 'STABLE',
    description: 'Low wildfire risk due to urban setting and distance from vegetated areas.',
    details: [
      'Urban area with limited vegetation',
      'Fire station within 1.2 miles',
      'No wildland-urban interface exposure',
    ],
    dataSource: 'USFS WUI',
    lastUpdated: new Date().toISOString(),
    firHazardSeverityZone: null,
    wildlandUrbanInterface: false,
    nearestFireStation: 1.2,
    vegetationDensity: 'Low',
  },
  wind: {
    level: 'VERY_HIGH',
    score: 85,
    trend: 'STABLE',
    description: 'High hurricane and wind risk typical of South Florida coastal areas.',
    details: [
      'Design wind speed: 175 mph (ASCE 7-22)',
      'Hurricane wind zone - Cat 4+ exposure',
      'Storm surge zone (Category 2+)',
    ],
    dataSource: 'ASCE 7 / NOAA SLOSH',
    lastUpdated: new Date().toISOString(),
    designWindSpeed: 175,
    hurricaneRisk: true,
    tornadoRisk: false,
    hailRisk: false,
  },
  earthquake: {
    level: 'LOW',
    score: 8,
    trend: 'STABLE',
    description: 'Minimal seismic risk in South Florida.',
    details: [
      'No significant fault lines within 200 miles',
      'Low seismic design category',
    ],
    dataSource: 'USGS NSHM',
    lastUpdated: new Date().toISOString(),
    seismicZone: 'Zone 0',
    nearestFaultLine: null,
    soilType: 'Limestone',
    liquidationPotential: null,
  },
  crime: {
    level: 'MODERATE',
    score: 45,
    trend: 'IMPROVING',
    description: 'Crime rates are near the national average for this area.',
    details: [
      'Violent crime index: 42 (national avg: 47)',
      'Property crime index: 51 (national avg: 52)',
      'Improving trend over past 3 years',
    ],
    dataSource: 'FBI UCR',
    lastUpdated: new Date().toISOString(),
    violentCrimeIndex: 42,
    propertyCrimeIndex: 51,
    nationalAverageDiff: -4.2,
  },
  generatedAt: new Date().toISOString(),
  cacheTtlSeconds: 86400,
}

export const mockInsurance: InsuranceCostEstimate = {
  propertyId: 'prop_1',
  estimatedAnnualTotal: 8450,
  estimatedMonthlyTotal: 704,
  confidenceLevel: 'MEDIUM',
  coverages: [
    {
      type: 'HOMEOWNERS',
      required: true,
      averageAnnualPremium: 3200,
      lowEstimate: 2800,
      highEstimate: 3800,
      notes: ['Standard HO-3 policy', 'Includes dwelling, liability, and contents'],
    },
    {
      type: 'FLOOD',
      required: true,
      averageAnnualPremium: 2850,
      lowEstimate: 2200,
      highEstimate: 3800,
      notes: ['Required for SFHA properties', 'NFIP or private flood available', 'Consider excess flood coverage'],
    },
    {
      type: 'WIND_HURRICANE',
      required: true,
      averageAnnualPremium: 2400,
      lowEstimate: 1800,
      highEstimate: 3200,
      notes: ['Separate wind policy required in FL', 'Citizens may be available as last resort'],
    },
  ],
  keyRiskFactors: [
    'High flood zone (AE) significantly increases flood premium',
    'Coastal wind exposure requires separate windstorm coverage',
    'Property age and condition affect base premium',
  ],
  recommendations: [
    'Consider elevation certificate to potentially reduce flood premium',
    'Shop private flood market - may offer better rates than NFIP',
    'Hurricane shutters or impact windows could reduce wind premium by 10-15%',
    'Bundle policies with same carrier for potential discount',
  ],
  disclaimers: [
    'Estimates are based on publicly available data and typical market rates. Actual premiums will vary based on detailed underwriting.',
    'This is not a quote or offer of insurance.',
  ],
  generatedAt: new Date().toISOString(),
}

export const mockCarriers: CarriersResult = {
  propertyId: 'prop_1',
  carriers: [
    {
      id: 'carrier_1',
      name: 'State Farm',
      amBestRating: 'A++',
      writingStatus: 'ACTIVELY_WRITING',
      coverageTypes: ['HOMEOWNERS', 'UMBRELLA'],
      avgPremiumModifier: 1.05,
      statesLicensed: ['FL', 'CA', 'TX', 'NY'],
      specialties: ['Standard homeowners', 'Multi-policy discounts'],
      notes: null,
    },
    {
      id: 'carrier_2',
      name: 'Citizens Property Insurance',
      amBestRating: 'A',
      writingStatus: 'ACTIVELY_WRITING',
      coverageTypes: ['HOMEOWNERS', 'WIND_HURRICANE', 'FLOOD'],
      avgPremiumModifier: 1.15,
      statesLicensed: ['FL'],
      specialties: ['Florida market of last resort', 'Wind-only policies'],
      notes: 'State-run insurer - available when private market unavailable',
    },
    {
      id: 'carrier_3',
      name: 'Universal Insurance',
      amBestRating: 'A-',
      writingStatus: 'ACTIVELY_WRITING',
      coverageTypes: ['HOMEOWNERS', 'FLOOD'],
      avgPremiumModifier: 0.95,
      statesLicensed: ['FL', 'GA', 'SC'],
      specialties: ['Florida specialists', 'Competitive coastal rates'],
      notes: null,
    },
    {
      id: 'carrier_4',
      name: 'Allstate',
      amBestRating: 'A+',
      writingStatus: 'LIMITED',
      coverageTypes: ['HOMEOWNERS', 'UMBRELLA'],
      avgPremiumModifier: 1.1,
      statesLicensed: ['FL', 'CA', 'TX', 'NY'],
      specialties: ['Standard homeowners'],
      notes: 'Limited new policies in high-risk coastal areas',
    },
    {
      id: 'carrier_5',
      name: 'Neptune Flood',
      amBestRating: 'A',
      writingStatus: 'ACTIVELY_WRITING',
      coverageTypes: ['FLOOD'],
      avgPremiumModifier: 0.9,
      statesLicensed: ['FL', 'CA', 'TX', 'LA', 'SC', 'NC'],
      specialties: ['Private flood insurance', 'Excess flood coverage'],
      notes: 'Often 10-20% below NFIP rates',
    },
  ],
  marketCondition: 'HARD',
  lastUpdated: new Date().toISOString(),
}

export const mockInsurability: InsurabilityStatus = {
  propertyId: 'prop_1',
  isInsurable: true,
  difficultyLevel: 'HIGH',
  potentialIssues: [
    'Located in Special Flood Hazard Area (SFHA) - flood insurance mandatory',
    'High wind zone (175 mph design speed) limits carrier availability',
    'Some carriers have moratoriums on new policies in this ZIP code',
    'May require wind mitigation inspection for best rates',
  ],
  recommendedActions: [
    'Obtain elevation certificate if not on file',
    'Get wind mitigation inspection to qualify for discounts',
    'Shop both NFIP and private flood market',
    'Consider Citizens as backup if private market declines',
    'Bundle policies where possible for multi-policy discounts',
  ],
}

export const mockAnalytics: AnalyticsSummary = {
  totalSearches: 847,
  totalSavedProperties: 32,
  totalClients: 18,
  totalReports: 156,
  searchesByDay: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(Date.now() - (29 - i) * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    count: Math.floor(Math.random() * 40) + 10,
  })),
  riskDistribution: [
    { level: 'LOW', count: 8 },
    { level: 'MODERATE', count: 12 },
    { level: 'HIGH', count: 9 },
    { level: 'VERY_HIGH', count: 3 },
  ],
  topStates: [
    { state: 'FL', count: 245 },
    { state: 'CA', count: 198 },
    { state: 'TX', count: 156 },
    { state: 'NY', count: 89 },
    { state: 'CO', count: 67 },
    { state: 'SC', count: 45 },
    { state: 'NC', count: 32 },
    { state: 'GA', count: 15 },
  ],
  recentActivity: [
    { description: 'Searched property at 123 Palm Beach Rd, Miami FL', timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString() },
    { description: 'Saved property to portfolio', timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString() },
    { description: 'Requested quote from Citizens Property Insurance', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
    { description: 'Added new client: John Smith', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString() },
    { description: 'Generated property report for 456 Sunset Blvd', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
    { description: 'Compared 3 properties in Miami-Dade County', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString() },
  ],
}

export const mockClients: Client[] = [
  {
    id: 'client_1',
    agentId: 'agent_1',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@email.com',
    phone: '(555) 123-4567',
    status: 'ACTIVE',
    notes: 'Looking for single family home in Miami area, budget $800k-1M',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client_2',
    agentId: 'agent_1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.j@email.com',
    phone: '(555) 987-6543',
    status: 'PROSPECT',
    notes: 'First-time homebuyer, interested in Austin TX',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'client_3',
    agentId: 'agent_1',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'm.chen@email.com',
    phone: null,
    status: 'CLOSED',
    notes: 'Closed on property at 789 Oak Street',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
]

export const mockUser: User = {
  id: 'user_1',
  email: 'agent@coverguard.com',
  firstName: 'Alex',
  lastName: 'Thompson',
  role: 'AGENT',
  company: 'Thompson Realty Group',
  licenseNumber: 'FL-RE-12345',
  termsAcceptedAt: new Date().toISOString(),
  createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
  updatedAt: new Date().toISOString(),
}
